apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-python-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: fastapi
  template:
    metadata:
      labels:
        service: fastapi
    spec:
      containers:
      - name: fastapi-service
        image: technox64/essential-test:latest
        imagePullPolicy: Always
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_DB
          value: example
        - name: MYSQL_SERVER
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
