# Generated by Django 5.0.7 on 2024-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='En', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]