# Generated by Django 5.0.7 on 2024-08-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_option_question_alter_question_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='book',
            field=models.CharField(default='E1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
