# Generated by Django 5.0.7 on 2024-08-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_book_alter_option_question'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='option',
        #     table='options',
        # ),
        # migrations.AlterModelTable(
        #     name='question',
        #     table='questions',
        # ),
        # migrations.AlterModelTable(
        #     name='quiz',
        #     table='quizzes',
        # ),
    ]