# Generated by Django 5.0.7 on 2024-08-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_option_table_alter_question_table_and_more'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='option',
        #     table='options',
        # ),
        # migrations.AlterModelTable(
        #     name='question',
        #     table='questions',
        # ),
        # migrations.AlterModelTable(
        #     name='quiz',
        #     table='quizzes',
        # ),
    ]
