# Generated by Django 5.0.7 on 2025-03-26 07:58

from django.db import migrations, models
import django.contrib.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_option_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-user.png', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=models.CASCADE, to='auth.User')),
            ],
        ),
    ]
