# Generated by Django 5.0.7 on 2025-03-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_recreate_profiles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
